name: RSpec

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: restore once 5.2 support is removed
        # ruby:
        #   - "2.5.x"
        #   - "2.6.x"
        #   - "2.7.x"
        #   - "3.0.x"
        # rails:
        #   - "5.2.0"
        #   - "6.0.0"
        #   - "6.1.0"
        rubies:
          - ["2.6", "5.2.0"]
          - ["2.6", "6.0.0"]
          - ["2.6", "6.1.0"]
          - ["2.7", "5.2.0"]
          - ["2.7", "6.0.0"]
          - ["2.7", "6.1.0"]
          - ["2.7", "7.0.0"]
          - ["3.0", "6.0.0"]
          - ["3.0", "6.1.0"]
          - ["3.0", "7.0.0"]
          - ["3.1", "6.0.0"]
          - ["3.1", "6.1.0"]
          - ["3.1", "7.0.0"]

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.rubies[0] }}
        bundler-cache: true
    - name: Apply Rails ${{ matrix.rubies[1] }} dependencies
      run: |
        echo "gem 'activemodel', '~> ${{ matrix.rubies[1] }}'" >> Gemfile
        echo "gem 'activerecord', '~> ${{ matrix.rubies[1] }}'" >> Gemfile
        echo "gem 'activesupport', '~> ${{ matrix.rubies[1] }}'" >> Gemfile
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
        sudo apt-get install redis-server
        bundle config unset deployment
        bundle update activemodel activerecord activesupport
    - name: Run RSpec
      run: |
        bundle exec rspec
